<?php

/**
 * SEO Country Data — Ship-to landing pages
 * Each country has unique content to avoid thin/duplicate page penalties.
 */
return [
    'uk' => [
        'name' => 'United Kingdom',
        'country_code' => 'GB',
        'transit_days' => '5–7',
        'starting_price' => '৳2,500',
        'restricted_items' => ['Fresh meat & dairy', 'Liquids over 100ml in hand luggage', 'Counterfeit branded goods', 'Soil and plant materials without phytosanitary certificates', 'Certain prescription medicines'],
        'diaspora_note' => 'The UK is home to one of the largest Bangladeshi diaspora communities, with over 600,000 British-Bangladeshis — many with roots in the Sylhet region. Whether you\'re sending homemade pitha to family in Tower Hamlets, shipping traditional jamdani sarees for a wedding in Birmingham, or posting documents to a student in Manchester, ExpressPeek connects Bangladesh to the UK with reliable, tracked delivery.',
        'popular_items' => ['Jamdani & Muslin sarees', 'Dried fish (shutki)', 'Panjabi & kameez sets', 'Handicrafts & Nakshi Kantha', 'Aarong products'],
        'seo_title' => 'Send Parcels from Bangladesh to UK | ExpressPeek Courier',
        'seo_description' => 'Ship parcels, documents, and gifts from Bangladesh to the United Kingdom. 5-7 day delivery from Dhaka to London, Birmingham, Manchester & all UK cities. Trusted by British-Bangladeshis.',
    ],
    'usa' => [
        'name' => 'United States',
        'country_code' => 'US',
        'transit_days' => '5–8',
        'starting_price' => '৳2,800',
        'restricted_items' => ['Food items without FDA clearance', 'Agricultural products (soil, seeds)', 'Certain textiles without proper labeling', 'Medications without prescription', 'Items over $800 require formal customs entry'],
        'diaspora_note' => 'The United States is home to a growing Bangladeshi-American community, particularly concentrated in New York City (Jackson Heights, Astoria), Los Angeles, Dallas, and the DC metro area. From sending Eid gifts to family in Queens to shipping commercial garment samples to buyers in Manhattan\'s fashion district, ExpressPeek provides fast, transparent shipping from Bangladesh to all 50 states.',
        'popular_items' => ['RMG samples & textiles', 'Traditional sweets (mishti)', 'Handicrafts', 'Documents & certificates', 'Personal effects'],
        'seo_title' => 'Send Parcels from Bangladesh to USA | ExpressPeek Courier',
        'seo_description' => 'Ship parcels and documents from Bangladesh to the United States. 5-8 day delivery to New York, Los Angeles, Dallas & all US cities. Trusted courier for Bangladeshi-Americans.',
    ],
    'saudi-arabia' => [
        'name' => 'Saudi Arabia',
        'country_code' => 'SA',
        'transit_days' => '4–6',
        'starting_price' => '৳2,200',
        'restricted_items' => ['Pork products', 'Alcohol', 'Religious materials of non-Islamic faiths (for personal use only)', 'Drone equipment without permit', 'Binoculars and telescopes'],
        'diaspora_note' => 'Saudi Arabia hosts one of the largest communities of Bangladeshi workers globally, with over 2.5 million Bangladeshis working across Riyadh, Jeddah, Dammam, and the Eastern Province. ExpressPeek serves probashi workers who need documents, clothing, and personal items sent from home, as well as families in Bangladesh sending care packages to loved ones working abroad.',
        'popular_items' => ['Personal documents & certificates', 'Clothing & lungi', 'Dry foods & spices', 'Mobile phones & electronics', 'Medicine (with prescription)'],
        'seo_title' => 'Send Parcels from Bangladesh to Saudi Arabia | ExpressPeek',
        'seo_description' => 'Ship parcels and documents from Bangladesh to Saudi Arabia. 4-6 day delivery to Riyadh, Jeddah & Dammam. Trusted courier for Bangladeshi workers in KSA.',
    ],
    'uae' => [
        'name' => 'United Arab Emirates',
        'country_code' => 'AE',
        'transit_days' => '3–5',
        'starting_price' => '৳2,000',
        'restricted_items' => ['Pork products', 'Alcohol', 'Gambling-related items', 'E-cigarettes and vaping products', 'Items depicting the UAE flag inappropriately'],
        'diaspora_note' => 'The UAE — particularly Dubai and Abu Dhabi — is a major destination for Bangladeshi professionals, construction workers, and entrepreneurs. With fast transit times of 3-5 days, ExpressPeek is the go-to service for sending documents to embassies, shipping personal goods, or receiving Bangladeshi products in the Emirates.',
        'popular_items' => ['Documents for visa processing', 'Personal clothing', 'Dry foods (muri, chanachur)', 'Handicrafts', 'Electronics accessories'],
        'seo_title' => 'Send Parcels from Bangladesh to UAE | ExpressPeek Dubai Courier',
        'seo_description' => 'Ship parcels from Bangladesh to UAE. 3-5 day delivery to Dubai, Abu Dhabi & Sharjah. Fast, affordable courier for Bangladeshis in the Emirates.',
    ],
    'australia' => [
        'name' => 'Australia',
        'country_code' => 'AU',
        'transit_days' => '6–9',
        'starting_price' => '৳3,000',
        'restricted_items' => ['All food items require strict biosecurity declarations', 'Soil, wood, and plant materials', 'Animal products (leather may require certification)', 'Traditional medicines containing banned substances', 'Wooden handicrafts may require fumigation'],
        'diaspora_note' => 'Australia\'s Bangladeshi community has grown rapidly, with significant populations in Sydney (Lakemba, Rockdale), Melbourne, Brisbane, and Adelaide. Australian biosecurity is among the world\'s strictest — ExpressPeek helps navigate these requirements so your parcels clear customs smoothly. From sending winter clothing to students in Melbourne to shipping wedding attire for family celebrations in Sydney, we handle it all.',
        'popular_items' => ['Clothing & textiles', 'Books & study materials', 'Dry spices (packaged, declared)', 'Documents & certificates', 'Personal effects'],
        'seo_title' => 'Send Parcels from Bangladesh to Australia | ExpressPeek',
        'seo_description' => 'Ship parcels from Bangladesh to Australia. 6-9 day delivery to Sydney, Melbourne & Brisbane. We help navigate strict Australian customs for hassle-free delivery.',
    ],
    'malaysia' => [
        'name' => 'Malaysia',
        'country_code' => 'MY',
        'transit_days' => '4–6',
        'starting_price' => '৳1,800',
        'restricted_items' => ['Non-halal food products', 'Printed materials deemed seditious', 'Weapons and weapon replicas', 'Counterfeit goods', 'Kratom and certain herbal products'],
        'diaspora_note' => 'Malaysia is home to a large Bangladeshi migrant worker community, primarily in Kuala Lumpur, Penang, and Johor. ExpressPeek provides affordable shipping for probashi workers who need personal items, documents, and medicines sent from Bangladesh. Our competitive rates and reliable tracking make us the preferred choice for regular shipments.',
        'popular_items' => ['Personal documents', 'Clothing', 'Dry foods & spices', 'Mobile phones', 'Medicine (with prescription)'],
        'seo_title' => 'Send Parcels from Bangladesh to Malaysia | ExpressPeek',
        'seo_description' => 'Ship parcels from Bangladesh to Malaysia. 4-6 day delivery to Kuala Lumpur, Penang & Johor. Affordable courier for Bangladeshi workers in Malaysia.',
    ],
    'canada' => [
        'name' => 'Canada',
        'country_code' => 'CA',
        'transit_days' => '6–9',
        'starting_price' => '৳2,800',
        'restricted_items' => ['Food items requiring CFIA permits', 'Plants and soil', 'Certain animal products', 'Prescription medications without documentation', 'Items over CAD 2,500 require formal customs declaration'],
        'diaspora_note' => 'Canada\'s Bangladeshi community is concentrated in Toronto (Danforth, Scarborough), Montreal, and Vancouver. Whether you\'re sending traditional clothing for a cultural event in Toronto, shipping study materials to a student at McGill, or posting business samples to a buyer in Vancouver, ExpressPeek delivers with full tracking and competitive rates.',
        'popular_items' => ['Clothing & sarees', 'Handicrafts', 'Documents & transcripts', 'Dry foods (properly packaged)', 'Personal effects'],
        'seo_title' => 'Send Parcels from Bangladesh to Canada | ExpressPeek',
        'seo_description' => 'Ship parcels from Bangladesh to Canada. 6-9 day delivery to Toronto, Montreal & Vancouver. Trusted courier for the Bangladeshi-Canadian community.',
    ],
];
